config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  get "search" => "search#search"

  root 'homes#top'
  get 'home/about' => 'homes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 belongs_to :user
 has_many :book_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy

 def favorited_by?(user)
  favorites.where(user_id: user.id).exists?
 end

 validates :title, presence: true
 validates :body, presence: true, length: {maximum: 200}
 
 def self.search(searches, keywords)
   if searches == "perfect_match"
	  @book = Book.where("title LIKE? OR body LIKE?", "#{keywords}", "#{keywords}")
   elsif searches == "forward_match"
    @book = Book.where("title LIKE? OR body LIKE?", "#{keywords}%", "#{keywords}%")
   elsif searches == "backward_match"
    @book = Book.where("title LIKE? OR body LIKE?", "%#{keywords}", "%#{keywords}")
   else
    @book = Book.where("title LIKE? OR body LIKE?", "%#{keywords}%", "%#{keywords}%")
   end
 end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image, destroy: false

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  
  def self.search(searches, keywords)
   if searches == "perfect_match"
	  @user = User.where("name LIKE?", "#{keywords}")
   elsif searches == "forward_match"
    @user = User.where("name LIKE?", "#{keywords}%")
   elsif searches == "backward_match"
    @user = User.where("name LIKE?", "%#{keywords}")
   else
    @user = User.where("name LIKE?", "%#{keywords}%")
   end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except:[:about, :top]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    comment = @book.book_comments.find(params[:id])
    comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if @user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end
  
  def search
    @range = params[:range]
    search = params[:search]
    keyword = params[:keyword]
    @books = User.search(search, keyword)
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: params[:book_id])
    @favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: params[:book_id])
    @favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
		@range = params[:range]
		@keyword = params[:keyword]
		
		if @range == "User"
			@users = User.search(params[:search], params[:keyword])
		else
			@books = Book.search(params[:search], params[:keyword])
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end
  
  def search
    @range = params[:range]
    search = params[:search]
    keyword = params[:keyword]
    @users = User.search(search, keyword)
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$("#comment_index").html("<%= j(render partial: "books/comment", locals: { book: @book, user: @book.user }) %>");
$("#comment_area")[0].reset();
<!--$("#comment_area").val("")-->

app/views/book_comments/destroy.js.erb
$("#comment_index").html("<%= j(render partial: "books/comment", locals: { book: @book, user: @user }) %>");

app/views/books/_comment.html.erb
<table class='table'>
  <tr>
    <td><%= link_to user_path(book.user) do %>
      <%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
      <%= book.user.name %>
      <% end %>
    </td>
    <td><%= link_to book.title, book_path(book) %></td>
    <td><%= book.body %></td>
    <% if user == current_user %>
      <td><%= link_to 'Edit', edit_book_path(book), class: "btn btn-sm btn-success edit_book_#{book.id}" %></td>
      <td><%= link_to 'Destroy', book_path(book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{book.id}"%></td>
    <% end %>
    
    <td id="favorite-btn-<%= book.id %>">
      <%= render partial: "favorites/favorite-btn",locals: {book: book } %>
    </td>

    <td id="comments">
      コメント数:<%= book.book_comments.length %>
    </td>
  </tr>
</table>

<table>
<div>
<% book.book_comments.each do |book_comment| %>
    <tr>
    <td>
      <%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
      <%= book_comment.user.name %>
      <%= book_comment.comment %>
    </td>
    <% if book_comment.user == current_user %>
    <td>
      <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class:"btn btn-danger", remote: true  %>
    </td>
    <% end %>
    </tr>
<% end %>
</div>
</table>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
              <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
            <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>

        <td id="favorite-btn-<%= book.id %>">
          <%= render partial: "favorites/favorite-btn",locals: {book: book } %>
        </td>

        <td id="comments">
          コメント数:<%= book.book_comments.count %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_searchform.html.erb
<% if user_signed_in? %>
  <%= form_with(url: search_path, local:true, method: :get,class:"search-form") do |f| %>
    <%= f.text_field :keyword, value: @keyword %>
    <%= f.select :range, options_for_select([["User"],["Book"]]) %>
    <%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward_match"],["後方一致","backward_match"],["部分一致","partial_match"]]) %>    
    <%= f.submit "検索", class:"search-btn" %>
  <% end %>
<% end %>
<br>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'searchform' %>
<% if @book.errors.any? %>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books, book: @book %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
      <div id="comment_index">
        <%= render partial: "books/comment", locals: { book: @book, user: @book.user } %>
      </div>

      <div>
        <%= form_with(model:[@book, @book_comment], remote: true, id: "comment_area") do |f| %>
          <%= f.text_area :comment, rows:"5", size:"80" %><br>
          <%= f.submit "送信" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if current_user != book.user %>
  <% if book.favorited_by?(current_user) %>
      <%= link_to book_favorites_path(book), class:"unlike-btn", remote: true, method: :delete do %>
        ♥<%= book.favorites.count %>
      <% end %>
  <% else %>
      <%= link_to book_favorites_path(book), remote: true, method: :post do %>
        ♥<%= book.favorites.count %>
      <% end %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-btn-<%= @book.id %>").html("<%= j(render partial: "favorites/favorite-btn",locals: { book: @book }) %>");

app/views/favorites/destroy.js.erb
$("#favorite-btn-<%= @book.id %>").html("<%= j(render partial: "favorites/favorite-btn",locals: { book: @book }) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>

<% if @users.any? %>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h6>ユーザーはいません</h6>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>

<% if @users.any? %>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h6>ユーザーはいません</h6>
<% end %>

app/views/search/search.html.erb
<% if user_signed_in? %>
  <%= form_with(url: search_path, local:true, method: :get,class:"search-form") do |f| %>
    <%= f.text_field :keyword, value: @keyword %>
    <%= f.select :range, options_for_select([["User"],["Book"]]) %>
    <%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward_match"],["後方一致","backward_match"],["部分一致","partial_match"]]) %>    
    <%= f.submit "検索", class:"search-btn" %>
  <% end %>
<% end %>
<br>


<% if @range == "User" %>
<h4><%= "Users search for  #{@keyword}" %></h4>
<table class='table table-hover table-inverse'>
<thead>  
  <tr>
    <th></th>
    <th>name</th>
    <th colspan="3"></th>
  </tr>
</thead>

<tbody>    
  <% @users.each do |user| %>
  <tr>
    <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
    <td><%= user.name %></td>
  </tr>
  <% end %>
</tbody>
</table>

<% else %>
<h4><%= "Books search for #{@keyword}" %></h4>

<table class='table table-hover table-inverse'>
<thead> 
  <tr>
    <th></th>
    <th>title</th>
    <th>opinion</th>
    <th colspan="3"></th>
  </tr>
</thead>

<tbody>
  <% @books.each do |book| %>
      <tr>
        <td><%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
      </tr>
  <% end %>
</tbody>
</table>

<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>

        <% if current_user != user %>
          <% if current_user.following?(user) %>
           <td><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></td>
          <% else %>
           <td><%= link_to "フォロー", user_relationships_path(user.id), method: :post %></td>
          <% end %>
        <% else %>
           <td></td>
        <% end %>

        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>

  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>

  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>

  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>

</table>

<div class='row'>
  <% if current_user == user %>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <% else %>
    <% if current_user.following?(user) %>
     <td><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %></td>
    <% else %>
     <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %></td>
    <% end %>
  <% end %>
</div>

app/views/users/_searchform.html.erb
<% if user_signed_in? %>
  <%= form_with(url: search_path, local:true, method: :get,class:"search-form") do |f| %>
    <%= f.text_field :keyword, value: @keyword %>
    <%= f.select :range, options_for_select([["User"],["Book"]]) %>
    <%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward_match"],["後方一致","backward_match"],["部分一致","partial_match"]]) %>    
    <%= f.submit "検索", class:"search-btn" %>
  <% end %>
<% end %>
<br>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'searchform' %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>